//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poliklinika20.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class analyzers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public analyzers()
        {
            this.completed_services = new HashSet<completed_services>();
        }
    
        public int id_analyzer { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> last_maintenance_date { get; set; }
        public string manufacture_year { get; set; }
        public bool is_archived { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<completed_services> completed_services { get; set; }
    }
}
