//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poliklinika20.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class completed_services
    {
        public int id_completed_service { get; set; }
        public int id_lab_technician { get; set; }
        public int id_order { get; set; }
        public int id_service { get; set; }
        public int id_analyzer { get; set; }
        public short completion_time_days { get; set; }
        public string service_status { get; set; }
        public Nullable<System.DateTime> comletion_date { get; set; }
        public bool is_archived { get; set; }
    
        public virtual analyzers analyzers { get; set; }
        public virtual orders orders { get; set; }
        public virtual services services { get; set; }
        public virtual users users { get; set; }
    }
}
