//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poliklinika20.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class emp_service
    {
        public int id_emp_service { get; set; }
        public int id_service { get; set; }
        public int id_employee { get; set; }
        public bool is_archived { get; set; }
    
        public virtual services services { get; set; }
        public virtual users users { get; set; }
    }
}
