//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poliklinika20.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class insurers_bills
    {
        public int id_insurers_bill { get; set; }
        public int id_order { get; set; }
        public int id_accountant { get; set; }
        public System.DateTime creation_date { get; set; }
        public bool is_archived { get; set; }
    
        public virtual orders orders { get; set; }
        public virtual users users { get; set; }
    }
}
