//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poliklinika20.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class polikEntities6 : DbContext
    {

        private static polikEntities6 _context; 
        public static polikEntities6 GetContext()
        {
            if (_context == null)
                _context = new polikEntities6();
            return _context;
        }

        public polikEntities6()
            : base("name=polikEntities6")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<analyzers> analyzers { get; set; }
        public virtual DbSet<completed_services> completed_services { get; set; }
        public virtual DbSet<emp_service> emp_service { get; set; }
        public virtual DbSet<insurers> insurers { get; set; }
        public virtual DbSet<insurers_bills> insurers_bills { get; set; }
        public virtual DbSet<orders> orders { get; set; }
        public virtual DbSet<patients> patients { get; set; }
        public virtual DbSet<roles> roles { get; set; }
        public virtual DbSet<services> services { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<visit_logs> visit_logs { get; set; }
    }
}
