//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poliklinika20.DB
{
    using System;
    using System.Collections.Generic;

    public partial class services
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public services()
        {
            this.completed_services = new HashSet<completed_services>();
            this.emp_service = new HashSet<emp_service>();
        }

        public int id_service { get; set; }
        public string name { get; set; }
        public decimal cost { get; set; }
        public short completion_period_days { get; set; }
        public short average_deviation_days { get; set; }
        public bool is_archived { get; set; }

        public string archived
        {
            get { return is_archived ? "Удален" : "Не удален"; }

        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<completed_services> completed_services { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<emp_service> emp_service { get; set; }
    }
}
