//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poliklinika20.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class visit_logs
    {
        public int id_log { get; set; }
        public int id_user { get; set; }
        public System.DateTime visit_time { get; set; }
        public bool is_archived { get; set; }
        public string ip { get; set; }
    
        public virtual users users { get; set; }
    }
}
